### ISSUE TITLE
Add image import and image save features

### ISSUE THREAD

**Issue by EddieOne** [autoyang/autoyang.github.io#1]
It's client side javascript, mostly just want to see the yang gang accomplish something. So it should be easy money. Plus the [bounty](https://www.bountysource.com/issues/77178202-add-image-import-and-image-save-features). 

Please visit the autoyang page here https://autoyang.github.io/ You will see a browse button. This is where the import image is needed. The idea is a person uploads their image and can add hats. Also note, the save button, once clicked, the JS should offer an image file that the user can save to their device.

**Comment by Sravanksk** [comment]
Can you please explain your requirement clearly , So that it will be easy to make some assumptions on the solution you are expecting.

**Comment by EddieOne** [comment]
Good idea, I will update the original post.

**Comment by UnicodingUnicorn** [comment]
I have the image importing part done. The image saving part is a bit of a pain, since the drag and drop is handled by interact.js on elements, rather than canvas. The way I see it, there are two ways of doing this:

1. Keep the original system, capturing the rendered state of a div the images are placed in using `html2canvas. I have tried this method out, and find it is a bit finicky.

2. Rewrite the dragging system to be wholly canvas based. This does mean forgoing the benefits interact.js provides.

**Comment by EddieOne** [comment]
That's good news. I would try html2canvas first. I'm not sure of any premade drag and resize solutions already made in canvas, so it could be more work than expected.

**Comment by EddieOne** [comment]
Oh wait, there is http://fabricjs.com/, I've have good success with that before.

**Comment by UnicodingUnicorn** [comment]
That's great, shall I leave you to it, or can I do it please?

**Comment by EddieOne** [comment]
Yes, you can handle it. thanks!
